os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: 24june_1000k16_02
      script: 
        - echo "condition with joppb test"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 5
